# Generated by Django 5.1.7 on 2025-04-08 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fun_quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일시'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일시'),
        ),
        migrations.AlterField(
            model_name='pastliferesult',
            name='past_life_name',
            field=models.CharField(blank=True, max_length=500, verbose_name='전생 이름'),
        ),
        migrations.AlterField(
            model_name='pastliferesult',
            name='result_image',
            field=models.CharField(blank=True, max_length=600, verbose_name='결과 이미지 URL'),
        ),
        migrations.AlterField(
            model_name='pastlifetest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일시'),
        ),
        migrations.AlterField(
            model_name='pastlifetest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일시'),
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('title', models.CharField(max_length=100, verbose_name='테스트 제목')),
                ('slug', models.SlugField(unique=True, verbose_name='URL용 이름')),
                ('decription', models.TextField(verbose_name='테스트 설명')),
                ('thumbnail', models.ImageField(upload_to='test/thumbnail', verbose_name='썸네일')),
                ('participant_count', models.PositiveIntegerField(default=0, verbose_name='참여자 수')),
                ('share_count', models.PositiveIntegerField(default=0, verbose_name='공유 수')),
                ('is_ai_image', models.BooleanField(default=False, verbose_name='AI 이미지 생성 여부')),
                ('prompt_template', models.TextField(blank=True, help_text='생년월일, 시간 등의 변수는 {birth_date}, {birth_time} 형식으로 입력', verbose_name='AI 이미지 생성 프롬프트 템플릿')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fun_quizzes.category', verbose_name='카테고리')),
            ],
            options={
                'verbose_name': '테스트',
                'verbose_name_plural': '테스트 목록',
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('ad_shown', models.BooleanField(default=False, verbose_name='광고 노출 여부')),
                ('ad_shown_at', models.DateTimeField(blank=True, null=True, verbose_name='광고 노출 시간')),
                ('birth_date', models.DateField(verbose_name='생년월일')),
                ('birth_time', models.TimeField(verbose_name='태어난 시간')),
                ('result_image', models.ImageField(blank=True, upload_to='test/result', verbose_name='결과 이미지')),
                ('extra_data', models.JSONField(blank=True, null=True, verbose_name='테스트별 추가 정보')),
                ('story_response', models.JSONField(blank=True, null=True, verbose_name='이야기 AI 응답 데이터')),
                ('image_response', models.JSONField(blank=True, null=True, verbose_name='이미지 AI 응답 데이터')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fun_quizzes.test', verbose_name='테스트')),
            ],
            options={
                'verbose_name': '테스트 결과',
                'verbose_name_plural': '테스트 결과 목록',
            },
        ),
    ]
